# Generated by Django 4.0.4 on 2023-02-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('text', models.TextField()),
                ('location_url', models.TextField(default='')),
                ('longitude', models.FloatField(default=None, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=16, unique=True, verbose_name='ID')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram nomi (@username)')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiyasi')),
                ('phone', models.CharField(default='-', max_length=25)),
                ('step', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram profil',
                'verbose_name_plural': 'Telegram profillar',
            },
        ),
    ]
