# Generated by Django 4.0.4 on 2023-02-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Savol-javob', 'verbose_name_plural': 'Savol-javoblar'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': "Ma'lumotlar", 'verbose_name_plural': "Ma'lumotlar"},
        ),
        migrations.AlterField(
            model_name='info',
            name='location_url',
            field=models.TextField(default=None, verbose_name='Google maps manzili'),
        ),
        migrations.AlterField(
            model_name='info',
            name='text',
            field=models.TextField(verbose_name='Matn'),
        ),
    ]
