# Generated by Django 4.0.4 on 2023-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_faq_options_alter_info_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='location_url',
            field=models.TextField(default=None, null=True, verbose_name='Google maps manzili'),
        ),
    ]
